/* This file was generated */
export type IconTypes = string |
 "arrow_down"|
"arrow_left"|
"arrow_right"|
"arrow_up"|
"arrow_up_right"|
"brand"|
"calendar"|
"check-circle"|
"check"|
"check_circle"|
"chevron_down"|
"chevron_left"|
"chevron_right"|
"chevron_up"|
"circle"|
"clock"|
"cross"|
"cross_circle"|
"exclamation_mark_circle"|
"exclamation_mark_triangle"|
"information_circle"|
"magnifying_glass"|
"menu"|
"minus"|
"plus"|
"resize_handle_corner"|
"x_placeholder";